# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.IntegerField(blank=True, default=1, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('verification', models.BooleanField()),
                ('show_name', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('1', 'administrator'), ('2', 'member')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
