# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_post_post_images_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_images',
            name='by',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_like',
            name='of_post_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
