# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('of_post_id', models.ManyToManyField(related_name='books', to='post.Post')),
            ],
        ),
    ]
