# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_images',
            name='of_post_id',
        ),
        migrations.AddField(
            model_name='post_images',
            name='of_post_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='post.Post'),
        ),
    ]
