# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_post_post_comments_post_images_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
