# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-05 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_post_comments_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_comments',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
